sudo: required

language: go

services:
  - docker

go:
  - 1.7

os:
  - linux
  - osx

before_install:
  - go get -v github.com/mattn/goveralls

install:
  - make setup-ci

script:
  - make build-all
  - make test-race
  - METALINTER_CONCURRENCY=2 make check
  - make bench-race
  - make coveralls

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" -a ! -z "$TRAVIS_TAG" ]; then
    echo "Executing release on tag build $TRAVIS_TAG";
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ARCH=linux make release;
    else
    echo "Not executing release on non-tag build";
    fi
